// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Claim struct {
	ID      int     `json:"id"`
	User    *User   `json:"user"`
	Service string  `json:"service"`
	Claims  *string `json:"claims,omitempty"`
}

type ClaimInput struct {
	UserID  *int    `json:"userId,omitempty"`
	Service *string `json:"service,omitempty"`
	Claims  *string `json:"claims,omitempty"`
}

type Group struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Email       string  `json:"email"`
	Users       []*User `json:"users,omitempty"`
}

type GroupInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	Email       *string `json:"email,omitempty"`
}

type Role struct {
	ID          int     `json:"id"`
	Name        string  `json:"name"`
	Description string  `json:"description"`
	Users       []*User `json:"users,omitempty"`
}

type RoleInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
}

type User struct {
	ID          int      `json:"id"`
	FullName    string   `json:"fullName"`
	Username    string   `json:"username"`
	Email       string   `json:"email"`
	Preferences *string  `json:"preferences,omitempty"`
	Roles       []*Role  `json:"roles,omitempty"`
	Groups      []*Group `json:"groups,omitempty"`
	Claims      []*Claim `json:"claims,omitempty"`
}

type UserGroupsInput struct {
	GroupIds []int `json:"groupIds"`
}

type UserInput struct {
	FullName    *string `json:"fullName,omitempty"`
	Username    *string `json:"username,omitempty"`
	Email       *string `json:"email,omitempty"`
	Password    *string `json:"password,omitempty"`
	Preferences *string `json:"preferences,omitempty"`
}

type UserRolesInput struct {
	RoleIds []int `json:"roleIds"`
}
