// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"com.cross-join.crossviewer.authService/business/data/ent/claim"
	"com.cross-join.crossviewer.authService/business/data/ent/predicate"
	"com.cross-join.crossviewer.authService/business/data/ent/user"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ClaimUpdate is the builder for updating Claim entities.
type ClaimUpdate struct {
	config
	hooks    []Hook
	mutation *ClaimMutation
}

// Where appends a list predicates to the ClaimUpdate builder.
func (cu *ClaimUpdate) Where(ps ...predicate.Claim) *ClaimUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetUserID sets the "user_id" field.
func (cu *ClaimUpdate) SetUserID(i int) *ClaimUpdate {
	cu.mutation.SetUserID(i)
	return cu
}

// SetService sets the "service" field.
func (cu *ClaimUpdate) SetService(s string) *ClaimUpdate {
	cu.mutation.SetService(s)
	return cu
}

// SetClaims sets the "claims" field.
func (cu *ClaimUpdate) SetClaims(s string) *ClaimUpdate {
	cu.mutation.SetClaims(s)
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *ClaimUpdate) SetCreatedAt(t time.Time) *ClaimUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *ClaimUpdate) SetNillableCreatedAt(t *time.Time) *ClaimUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *ClaimUpdate) SetUpdatedAt(t time.Time) *ClaimUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cu *ClaimUpdate) SetNillableUpdatedAt(t *time.Time) *ClaimUpdate {
	if t != nil {
		cu.SetUpdatedAt(*t)
	}
	return cu
}

// SetUser sets the "user" edge to the User entity.
func (cu *ClaimUpdate) SetUser(u *User) *ClaimUpdate {
	return cu.SetUserID(u.ID)
}

// Mutation returns the ClaimMutation object of the builder.
func (cu *ClaimUpdate) Mutation() *ClaimMutation {
	return cu.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cu *ClaimUpdate) ClearUser() *ClaimUpdate {
	cu.mutation.ClearUser()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ClaimUpdate) Save(ctx context.Context) (int, error) {
	return withHooks[int, ClaimMutation](ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ClaimUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ClaimUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ClaimUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ClaimUpdate) check() error {
	if _, ok := cu.mutation.UserID(); cu.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Claim.user"`)
	}
	return nil
}

func (cu *ClaimUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(claim.Table, claim.Columns, sqlgraph.NewFieldSpec(claim.FieldID, field.TypeInt))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Service(); ok {
		_spec.SetField(claim.FieldService, field.TypeString, value)
	}
	if value, ok := cu.mutation.Claims(); ok {
		_spec.SetField(claim.FieldClaims, field.TypeString, value)
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.SetField(claim.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(claim.FieldUpdatedAt, field.TypeTime, value)
	}
	if cu.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claim.UserTable,
			Columns: []string{claim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claim.UserTable,
			Columns: []string{claim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{claim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ClaimUpdateOne is the builder for updating a single Claim entity.
type ClaimUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClaimMutation
}

// SetUserID sets the "user_id" field.
func (cuo *ClaimUpdateOne) SetUserID(i int) *ClaimUpdateOne {
	cuo.mutation.SetUserID(i)
	return cuo
}

// SetService sets the "service" field.
func (cuo *ClaimUpdateOne) SetService(s string) *ClaimUpdateOne {
	cuo.mutation.SetService(s)
	return cuo
}

// SetClaims sets the "claims" field.
func (cuo *ClaimUpdateOne) SetClaims(s string) *ClaimUpdateOne {
	cuo.mutation.SetClaims(s)
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *ClaimUpdateOne) SetCreatedAt(t time.Time) *ClaimUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *ClaimUpdateOne) SetNillableCreatedAt(t *time.Time) *ClaimUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *ClaimUpdateOne) SetUpdatedAt(t time.Time) *ClaimUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cuo *ClaimUpdateOne) SetNillableUpdatedAt(t *time.Time) *ClaimUpdateOne {
	if t != nil {
		cuo.SetUpdatedAt(*t)
	}
	return cuo
}

// SetUser sets the "user" edge to the User entity.
func (cuo *ClaimUpdateOne) SetUser(u *User) *ClaimUpdateOne {
	return cuo.SetUserID(u.ID)
}

// Mutation returns the ClaimMutation object of the builder.
func (cuo *ClaimUpdateOne) Mutation() *ClaimMutation {
	return cuo.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (cuo *ClaimUpdateOne) ClearUser() *ClaimUpdateOne {
	cuo.mutation.ClearUser()
	return cuo
}

// Where appends a list predicates to the ClaimUpdate builder.
func (cuo *ClaimUpdateOne) Where(ps ...predicate.Claim) *ClaimUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ClaimUpdateOne) Select(field string, fields ...string) *ClaimUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Claim entity.
func (cuo *ClaimUpdateOne) Save(ctx context.Context) (*Claim, error) {
	return withHooks[*Claim, ClaimMutation](ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ClaimUpdateOne) SaveX(ctx context.Context) *Claim {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ClaimUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ClaimUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ClaimUpdateOne) check() error {
	if _, ok := cuo.mutation.UserID(); cuo.mutation.UserCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Claim.user"`)
	}
	return nil
}

func (cuo *ClaimUpdateOne) sqlSave(ctx context.Context) (_node *Claim, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(claim.Table, claim.Columns, sqlgraph.NewFieldSpec(claim.FieldID, field.TypeInt))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Claim.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, claim.FieldID)
		for _, f := range fields {
			if !claim.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != claim.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Service(); ok {
		_spec.SetField(claim.FieldService, field.TypeString, value)
	}
	if value, ok := cuo.mutation.Claims(); ok {
		_spec.SetField(claim.FieldClaims, field.TypeString, value)
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.SetField(claim.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(claim.FieldUpdatedAt, field.TypeTime, value)
	}
	if cuo.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claim.UserTable,
			Columns: []string{claim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   claim.UserTable,
			Columns: []string{claim.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Claim{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{claim.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
