// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"com.cross-join.crossviewer.authService/business/data/ent/group"
	"com.cross-join.crossviewer.authService/business/data/ent/predicate"
	"com.cross-join.crossviewer.authService/business/data/ent/user"
	"com.cross-join.crossviewer.authService/business/data/ent/usersgroups"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsersGroupsQuery is the builder for querying UsersGroups entities.
type UsersGroupsQuery struct {
	config
	ctx        *QueryContext
	order      []usersgroups.OrderOption
	inters     []Interceptor
	predicates []predicate.UsersGroups
	withUser   *UserQuery
	withRoles  *GroupQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UsersGroupsQuery builder.
func (ugq *UsersGroupsQuery) Where(ps ...predicate.UsersGroups) *UsersGroupsQuery {
	ugq.predicates = append(ugq.predicates, ps...)
	return ugq
}

// Limit the number of records to be returned by this query.
func (ugq *UsersGroupsQuery) Limit(limit int) *UsersGroupsQuery {
	ugq.ctx.Limit = &limit
	return ugq
}

// Offset to start from.
func (ugq *UsersGroupsQuery) Offset(offset int) *UsersGroupsQuery {
	ugq.ctx.Offset = &offset
	return ugq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ugq *UsersGroupsQuery) Unique(unique bool) *UsersGroupsQuery {
	ugq.ctx.Unique = &unique
	return ugq
}

// Order specifies how the records should be ordered.
func (ugq *UsersGroupsQuery) Order(o ...usersgroups.OrderOption) *UsersGroupsQuery {
	ugq.order = append(ugq.order, o...)
	return ugq
}

// QueryUser chains the current query on the "user" edge.
func (ugq *UsersGroupsQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: ugq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ugq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ugq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usersgroups.Table, usersgroups.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, usersgroups.UserTable, usersgroups.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(ugq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoles chains the current query on the "roles" edge.
func (ugq *UsersGroupsQuery) QueryRoles() *GroupQuery {
	query := (&GroupClient{config: ugq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := ugq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := ugq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usersgroups.Table, usersgroups.FieldID, selector),
			sqlgraph.To(group.Table, group.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, usersgroups.RolesTable, usersgroups.RolesColumn),
		)
		fromU = sqlgraph.SetNeighbors(ugq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UsersGroups entity from the query.
// Returns a *NotFoundError when no UsersGroups was found.
func (ugq *UsersGroupsQuery) First(ctx context.Context) (*UsersGroups, error) {
	nodes, err := ugq.Limit(1).All(setContextOp(ctx, ugq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usersgroups.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ugq *UsersGroupsQuery) FirstX(ctx context.Context) *UsersGroups {
	node, err := ugq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UsersGroups ID from the query.
// Returns a *NotFoundError when no UsersGroups ID was found.
func (ugq *UsersGroupsQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ugq.Limit(1).IDs(setContextOp(ctx, ugq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usersgroups.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ugq *UsersGroupsQuery) FirstIDX(ctx context.Context) int {
	id, err := ugq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UsersGroups entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UsersGroups entity is found.
// Returns a *NotFoundError when no UsersGroups entities are found.
func (ugq *UsersGroupsQuery) Only(ctx context.Context) (*UsersGroups, error) {
	nodes, err := ugq.Limit(2).All(setContextOp(ctx, ugq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usersgroups.Label}
	default:
		return nil, &NotSingularError{usersgroups.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ugq *UsersGroupsQuery) OnlyX(ctx context.Context) *UsersGroups {
	node, err := ugq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UsersGroups ID in the query.
// Returns a *NotSingularError when more than one UsersGroups ID is found.
// Returns a *NotFoundError when no entities are found.
func (ugq *UsersGroupsQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ugq.Limit(2).IDs(setContextOp(ctx, ugq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usersgroups.Label}
	default:
		err = &NotSingularError{usersgroups.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ugq *UsersGroupsQuery) OnlyIDX(ctx context.Context) int {
	id, err := ugq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UsersGroupsSlice.
func (ugq *UsersGroupsQuery) All(ctx context.Context) ([]*UsersGroups, error) {
	ctx = setContextOp(ctx, ugq.ctx, "All")
	if err := ugq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UsersGroups, *UsersGroupsQuery]()
	return withInterceptors[[]*UsersGroups](ctx, ugq, qr, ugq.inters)
}

// AllX is like All, but panics if an error occurs.
func (ugq *UsersGroupsQuery) AllX(ctx context.Context) []*UsersGroups {
	nodes, err := ugq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UsersGroups IDs.
func (ugq *UsersGroupsQuery) IDs(ctx context.Context) (ids []int, err error) {
	if ugq.ctx.Unique == nil && ugq.path != nil {
		ugq.Unique(true)
	}
	ctx = setContextOp(ctx, ugq.ctx, "IDs")
	if err = ugq.Select(usersgroups.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ugq *UsersGroupsQuery) IDsX(ctx context.Context) []int {
	ids, err := ugq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ugq *UsersGroupsQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, ugq.ctx, "Count")
	if err := ugq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, ugq, querierCount[*UsersGroupsQuery](), ugq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (ugq *UsersGroupsQuery) CountX(ctx context.Context) int {
	count, err := ugq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ugq *UsersGroupsQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, ugq.ctx, "Exist")
	switch _, err := ugq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (ugq *UsersGroupsQuery) ExistX(ctx context.Context) bool {
	exist, err := ugq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UsersGroupsQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ugq *UsersGroupsQuery) Clone() *UsersGroupsQuery {
	if ugq == nil {
		return nil
	}
	return &UsersGroupsQuery{
		config:     ugq.config,
		ctx:        ugq.ctx.Clone(),
		order:      append([]usersgroups.OrderOption{}, ugq.order...),
		inters:     append([]Interceptor{}, ugq.inters...),
		predicates: append([]predicate.UsersGroups{}, ugq.predicates...),
		withUser:   ugq.withUser.Clone(),
		withRoles:  ugq.withRoles.Clone(),
		// clone intermediate query.
		sql:  ugq.sql.Clone(),
		path: ugq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (ugq *UsersGroupsQuery) WithUser(opts ...func(*UserQuery)) *UsersGroupsQuery {
	query := (&UserClient{config: ugq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ugq.withUser = query
	return ugq
}

// WithRoles tells the query-builder to eager-load the nodes that are connected to
// the "roles" edge. The optional arguments are used to configure the query builder of the edge.
func (ugq *UsersGroupsQuery) WithRoles(opts ...func(*GroupQuery)) *UsersGroupsQuery {
	query := (&GroupClient{config: ugq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	ugq.withRoles = query
	return ugq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UsersGroups.Query().
//		GroupBy(usersgroups.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (ugq *UsersGroupsQuery) GroupBy(field string, fields ...string) *UsersGroupsGroupBy {
	ugq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UsersGroupsGroupBy{build: ugq}
	grbuild.flds = &ugq.ctx.Fields
	grbuild.label = usersgroups.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.UsersGroups.Query().
//		Select(usersgroups.FieldUserID).
//		Scan(ctx, &v)
func (ugq *UsersGroupsQuery) Select(fields ...string) *UsersGroupsSelect {
	ugq.ctx.Fields = append(ugq.ctx.Fields, fields...)
	sbuild := &UsersGroupsSelect{UsersGroupsQuery: ugq}
	sbuild.label = usersgroups.Label
	sbuild.flds, sbuild.scan = &ugq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UsersGroupsSelect configured with the given aggregations.
func (ugq *UsersGroupsQuery) Aggregate(fns ...AggregateFunc) *UsersGroupsSelect {
	return ugq.Select().Aggregate(fns...)
}

func (ugq *UsersGroupsQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range ugq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, ugq); err != nil {
				return err
			}
		}
	}
	for _, f := range ugq.ctx.Fields {
		if !usersgroups.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ugq.path != nil {
		prev, err := ugq.path(ctx)
		if err != nil {
			return err
		}
		ugq.sql = prev
	}
	return nil
}

func (ugq *UsersGroupsQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UsersGroups, error) {
	var (
		nodes       = []*UsersGroups{}
		_spec       = ugq.querySpec()
		loadedTypes = [2]bool{
			ugq.withUser != nil,
			ugq.withRoles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UsersGroups).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UsersGroups{config: ugq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, ugq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := ugq.withUser; query != nil {
		if err := ugq.loadUser(ctx, query, nodes, nil,
			func(n *UsersGroups, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := ugq.withRoles; query != nil {
		if err := ugq.loadRoles(ctx, query, nodes, nil,
			func(n *UsersGroups, e *Group) { n.Edges.Roles = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (ugq *UsersGroupsQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UsersGroups, init func(*UsersGroups), assign func(*UsersGroups, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UsersGroups)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (ugq *UsersGroupsQuery) loadRoles(ctx context.Context, query *GroupQuery, nodes []*UsersGroups, init func(*UsersGroups), assign func(*UsersGroups, *Group)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UsersGroups)
	for i := range nodes {
		fk := nodes[i].GroupID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(group.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "group_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (ugq *UsersGroupsQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ugq.querySpec()
	_spec.Node.Columns = ugq.ctx.Fields
	if len(ugq.ctx.Fields) > 0 {
		_spec.Unique = ugq.ctx.Unique != nil && *ugq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, ugq.driver, _spec)
}

func (ugq *UsersGroupsQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usersgroups.Table, usersgroups.Columns, sqlgraph.NewFieldSpec(usersgroups.FieldID, field.TypeInt))
	_spec.From = ugq.sql
	if unique := ugq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if ugq.path != nil {
		_spec.Unique = true
	}
	if fields := ugq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersgroups.FieldID)
		for i := range fields {
			if fields[i] != usersgroups.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if ugq.withUser != nil {
			_spec.Node.AddColumnOnce(usersgroups.FieldUserID)
		}
		if ugq.withRoles != nil {
			_spec.Node.AddColumnOnce(usersgroups.FieldGroupID)
		}
	}
	if ps := ugq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ugq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ugq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ugq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ugq *UsersGroupsQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ugq.driver.Dialect())
	t1 := builder.Table(usersgroups.Table)
	columns := ugq.ctx.Fields
	if len(columns) == 0 {
		columns = usersgroups.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ugq.sql != nil {
		selector = ugq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if ugq.ctx.Unique != nil && *ugq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range ugq.predicates {
		p(selector)
	}
	for _, p := range ugq.order {
		p(selector)
	}
	if offset := ugq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ugq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UsersGroupsGroupBy is the group-by builder for UsersGroups entities.
type UsersGroupsGroupBy struct {
	selector
	build *UsersGroupsQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (uggb *UsersGroupsGroupBy) Aggregate(fns ...AggregateFunc) *UsersGroupsGroupBy {
	uggb.fns = append(uggb.fns, fns...)
	return uggb
}

// Scan applies the selector query and scans the result into the given value.
func (uggb *UsersGroupsGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, uggb.build.ctx, "GroupBy")
	if err := uggb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsersGroupsQuery, *UsersGroupsGroupBy](ctx, uggb.build, uggb, uggb.build.inters, v)
}

func (uggb *UsersGroupsGroupBy) sqlScan(ctx context.Context, root *UsersGroupsQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(uggb.fns))
	for _, fn := range uggb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*uggb.flds)+len(uggb.fns))
		for _, f := range *uggb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*uggb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := uggb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UsersGroupsSelect is the builder for selecting fields of UsersGroups entities.
type UsersGroupsSelect struct {
	*UsersGroupsQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ugs *UsersGroupsSelect) Aggregate(fns ...AggregateFunc) *UsersGroupsSelect {
	ugs.fns = append(ugs.fns, fns...)
	return ugs
}

// Scan applies the selector query and scans the result into the given value.
func (ugs *UsersGroupsSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ugs.ctx, "Select")
	if err := ugs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsersGroupsQuery, *UsersGroupsSelect](ctx, ugs.UsersGroupsQuery, ugs, ugs.inters, v)
}

func (ugs *UsersGroupsSelect) sqlScan(ctx context.Context, root *UsersGroupsQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ugs.fns))
	for _, fn := range ugs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ugs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ugs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
