// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"com.cross-join.crossviewer.authService/business/data/ent/predicate"
	"com.cross-join.crossviewer.authService/business/data/ent/role"
	"com.cross-join.crossviewer.authService/business/data/ent/user"
	"com.cross-join.crossviewer.authService/business/data/ent/usersroles"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// UsersRolesQuery is the builder for querying UsersRoles entities.
type UsersRolesQuery struct {
	config
	ctx        *QueryContext
	order      []usersroles.OrderOption
	inters     []Interceptor
	predicates []predicate.UsersRoles
	withUser   *UserQuery
	withRoles  *RoleQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the UsersRolesQuery builder.
func (urq *UsersRolesQuery) Where(ps ...predicate.UsersRoles) *UsersRolesQuery {
	urq.predicates = append(urq.predicates, ps...)
	return urq
}

// Limit the number of records to be returned by this query.
func (urq *UsersRolesQuery) Limit(limit int) *UsersRolesQuery {
	urq.ctx.Limit = &limit
	return urq
}

// Offset to start from.
func (urq *UsersRolesQuery) Offset(offset int) *UsersRolesQuery {
	urq.ctx.Offset = &offset
	return urq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (urq *UsersRolesQuery) Unique(unique bool) *UsersRolesQuery {
	urq.ctx.Unique = &unique
	return urq
}

// Order specifies how the records should be ordered.
func (urq *UsersRolesQuery) Order(o ...usersroles.OrderOption) *UsersRolesQuery {
	urq.order = append(urq.order, o...)
	return urq
}

// QueryUser chains the current query on the "user" edge.
func (urq *UsersRolesQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: urq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := urq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := urq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usersroles.Table, usersroles.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, usersroles.UserTable, usersroles.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(urq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryRoles chains the current query on the "roles" edge.
func (urq *UsersRolesQuery) QueryRoles() *RoleQuery {
	query := (&RoleClient{config: urq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := urq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := urq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(usersroles.Table, usersroles.FieldID, selector),
			sqlgraph.To(role.Table, role.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, usersroles.RolesTable, usersroles.RolesColumn),
		)
		fromU = sqlgraph.SetNeighbors(urq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first UsersRoles entity from the query.
// Returns a *NotFoundError when no UsersRoles was found.
func (urq *UsersRolesQuery) First(ctx context.Context) (*UsersRoles, error) {
	nodes, err := urq.Limit(1).All(setContextOp(ctx, urq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{usersroles.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (urq *UsersRolesQuery) FirstX(ctx context.Context) *UsersRoles {
	node, err := urq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first UsersRoles ID from the query.
// Returns a *NotFoundError when no UsersRoles ID was found.
func (urq *UsersRolesQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = urq.Limit(1).IDs(setContextOp(ctx, urq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{usersroles.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (urq *UsersRolesQuery) FirstIDX(ctx context.Context) int {
	id, err := urq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single UsersRoles entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one UsersRoles entity is found.
// Returns a *NotFoundError when no UsersRoles entities are found.
func (urq *UsersRolesQuery) Only(ctx context.Context) (*UsersRoles, error) {
	nodes, err := urq.Limit(2).All(setContextOp(ctx, urq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{usersroles.Label}
	default:
		return nil, &NotSingularError{usersroles.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (urq *UsersRolesQuery) OnlyX(ctx context.Context) *UsersRoles {
	node, err := urq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only UsersRoles ID in the query.
// Returns a *NotSingularError when more than one UsersRoles ID is found.
// Returns a *NotFoundError when no entities are found.
func (urq *UsersRolesQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = urq.Limit(2).IDs(setContextOp(ctx, urq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{usersroles.Label}
	default:
		err = &NotSingularError{usersroles.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (urq *UsersRolesQuery) OnlyIDX(ctx context.Context) int {
	id, err := urq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of UsersRolesSlice.
func (urq *UsersRolesQuery) All(ctx context.Context) ([]*UsersRoles, error) {
	ctx = setContextOp(ctx, urq.ctx, "All")
	if err := urq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*UsersRoles, *UsersRolesQuery]()
	return withInterceptors[[]*UsersRoles](ctx, urq, qr, urq.inters)
}

// AllX is like All, but panics if an error occurs.
func (urq *UsersRolesQuery) AllX(ctx context.Context) []*UsersRoles {
	nodes, err := urq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of UsersRoles IDs.
func (urq *UsersRolesQuery) IDs(ctx context.Context) (ids []int, err error) {
	if urq.ctx.Unique == nil && urq.path != nil {
		urq.Unique(true)
	}
	ctx = setContextOp(ctx, urq.ctx, "IDs")
	if err = urq.Select(usersroles.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (urq *UsersRolesQuery) IDsX(ctx context.Context) []int {
	ids, err := urq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (urq *UsersRolesQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, urq.ctx, "Count")
	if err := urq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, urq, querierCount[*UsersRolesQuery](), urq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (urq *UsersRolesQuery) CountX(ctx context.Context) int {
	count, err := urq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (urq *UsersRolesQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, urq.ctx, "Exist")
	switch _, err := urq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (urq *UsersRolesQuery) ExistX(ctx context.Context) bool {
	exist, err := urq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the UsersRolesQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (urq *UsersRolesQuery) Clone() *UsersRolesQuery {
	if urq == nil {
		return nil
	}
	return &UsersRolesQuery{
		config:     urq.config,
		ctx:        urq.ctx.Clone(),
		order:      append([]usersroles.OrderOption{}, urq.order...),
		inters:     append([]Interceptor{}, urq.inters...),
		predicates: append([]predicate.UsersRoles{}, urq.predicates...),
		withUser:   urq.withUser.Clone(),
		withRoles:  urq.withRoles.Clone(),
		// clone intermediate query.
		sql:  urq.sql.Clone(),
		path: urq.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (urq *UsersRolesQuery) WithUser(opts ...func(*UserQuery)) *UsersRolesQuery {
	query := (&UserClient{config: urq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	urq.withUser = query
	return urq
}

// WithRoles tells the query-builder to eager-load the nodes that are connected to
// the "roles" edge. The optional arguments are used to configure the query builder of the edge.
func (urq *UsersRolesQuery) WithRoles(opts ...func(*RoleQuery)) *UsersRolesQuery {
	query := (&RoleClient{config: urq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	urq.withRoles = query
	return urq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.UsersRoles.Query().
//		GroupBy(usersroles.FieldUserID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (urq *UsersRolesQuery) GroupBy(field string, fields ...string) *UsersRolesGroupBy {
	urq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &UsersRolesGroupBy{build: urq}
	grbuild.flds = &urq.ctx.Fields
	grbuild.label = usersroles.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UserID int `json:"user_id,omitempty"`
//	}
//
//	client.UsersRoles.Query().
//		Select(usersroles.FieldUserID).
//		Scan(ctx, &v)
func (urq *UsersRolesQuery) Select(fields ...string) *UsersRolesSelect {
	urq.ctx.Fields = append(urq.ctx.Fields, fields...)
	sbuild := &UsersRolesSelect{UsersRolesQuery: urq}
	sbuild.label = usersroles.Label
	sbuild.flds, sbuild.scan = &urq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a UsersRolesSelect configured with the given aggregations.
func (urq *UsersRolesQuery) Aggregate(fns ...AggregateFunc) *UsersRolesSelect {
	return urq.Select().Aggregate(fns...)
}

func (urq *UsersRolesQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range urq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, urq); err != nil {
				return err
			}
		}
	}
	for _, f := range urq.ctx.Fields {
		if !usersroles.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if urq.path != nil {
		prev, err := urq.path(ctx)
		if err != nil {
			return err
		}
		urq.sql = prev
	}
	return nil
}

func (urq *UsersRolesQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*UsersRoles, error) {
	var (
		nodes       = []*UsersRoles{}
		_spec       = urq.querySpec()
		loadedTypes = [2]bool{
			urq.withUser != nil,
			urq.withRoles != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*UsersRoles).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &UsersRoles{config: urq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, urq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := urq.withUser; query != nil {
		if err := urq.loadUser(ctx, query, nodes, nil,
			func(n *UsersRoles, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := urq.withRoles; query != nil {
		if err := urq.loadRoles(ctx, query, nodes, nil,
			func(n *UsersRoles, e *Role) { n.Edges.Roles = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (urq *UsersRolesQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*UsersRoles, init func(*UsersRoles), assign func(*UsersRoles, *User)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UsersRoles)
	for i := range nodes {
		fk := nodes[i].UserID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "user_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (urq *UsersRolesQuery) loadRoles(ctx context.Context, query *RoleQuery, nodes []*UsersRoles, init func(*UsersRoles), assign func(*UsersRoles, *Role)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*UsersRoles)
	for i := range nodes {
		fk := nodes[i].RoleID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(role.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "role_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (urq *UsersRolesQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := urq.querySpec()
	_spec.Node.Columns = urq.ctx.Fields
	if len(urq.ctx.Fields) > 0 {
		_spec.Unique = urq.ctx.Unique != nil && *urq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, urq.driver, _spec)
}

func (urq *UsersRolesQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(usersroles.Table, usersroles.Columns, sqlgraph.NewFieldSpec(usersroles.FieldID, field.TypeInt))
	_spec.From = urq.sql
	if unique := urq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if urq.path != nil {
		_spec.Unique = true
	}
	if fields := urq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, usersroles.FieldID)
		for i := range fields {
			if fields[i] != usersroles.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if urq.withUser != nil {
			_spec.Node.AddColumnOnce(usersroles.FieldUserID)
		}
		if urq.withRoles != nil {
			_spec.Node.AddColumnOnce(usersroles.FieldRoleID)
		}
	}
	if ps := urq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := urq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := urq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := urq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (urq *UsersRolesQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(urq.driver.Dialect())
	t1 := builder.Table(usersroles.Table)
	columns := urq.ctx.Fields
	if len(columns) == 0 {
		columns = usersroles.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if urq.sql != nil {
		selector = urq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if urq.ctx.Unique != nil && *urq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range urq.predicates {
		p(selector)
	}
	for _, p := range urq.order {
		p(selector)
	}
	if offset := urq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := urq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// UsersRolesGroupBy is the group-by builder for UsersRoles entities.
type UsersRolesGroupBy struct {
	selector
	build *UsersRolesQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (urgb *UsersRolesGroupBy) Aggregate(fns ...AggregateFunc) *UsersRolesGroupBy {
	urgb.fns = append(urgb.fns, fns...)
	return urgb
}

// Scan applies the selector query and scans the result into the given value.
func (urgb *UsersRolesGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, urgb.build.ctx, "GroupBy")
	if err := urgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsersRolesQuery, *UsersRolesGroupBy](ctx, urgb.build, urgb, urgb.build.inters, v)
}

func (urgb *UsersRolesGroupBy) sqlScan(ctx context.Context, root *UsersRolesQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(urgb.fns))
	for _, fn := range urgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*urgb.flds)+len(urgb.fns))
		for _, f := range *urgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*urgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := urgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// UsersRolesSelect is the builder for selecting fields of UsersRoles entities.
type UsersRolesSelect struct {
	*UsersRolesQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (urs *UsersRolesSelect) Aggregate(fns ...AggregateFunc) *UsersRolesSelect {
	urs.fns = append(urs.fns, fns...)
	return urs
}

// Scan applies the selector query and scans the result into the given value.
func (urs *UsersRolesSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, urs.ctx, "Select")
	if err := urs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*UsersRolesQuery, *UsersRolesSelect](ctx, urs.UsersRolesQuery, urs, urs.inters, v)
}

func (urs *UsersRolesSelect) sqlScan(ctx context.Context, root *UsersRolesQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(urs.fns))
	for _, fn := range urs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*urs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := urs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
