version: "3.9"
services:
  auth:
    image: auth
    build:
      context: ./../../
      dockerfile: ./zarf/docker/Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - db
      - otel
  db:
    image: db
    build:
      context: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
  otel:
    image: otel:latest
    build:
      context: ./otel
    ports:
      - "4317:4317"
      - "4318:4318"
#    volumes:
#      - type: bind
#        source: ./zarf/docker/otel/collector.yaml
#        target: /collector.yaml
#    entrypoint:
#
##      - "/otelcol-contrib"
##      - "--config=/collector.yaml"