version: "3.9"
services:
  auth:
    image: auth
    build:
      context: ./../../
      dockerfile: ./zarf/docker/Dockerfile
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      - db
      - otel
  db:
    image: db
    build:
      context: ./db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
  otel:
    image: jaegertracing/all-in-one:1.6
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"