// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Claim is the predicate function for claim builders.
type Claim func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// Role is the predicate function for role builders.
type Role func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// UsersGroups is the predicate function for usersgroups builders.
type UsersGroups func(*sql.Selector)

// UsersRoles is the predicate function for usersroles builders.
type UsersRoles func(*sql.Selector)
