package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.30

import (
	"context"
	"fmt"
)

// E is the resolver for the e field.
func (r *mutationResolver) E(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: E - e"))
}

// E is the resolver for the e field.
func (r *queryResolver) E(ctx context.Context) (*bool, error) {
	panic(fmt.Errorf("not implemented: E - e"))
}

// E is the resolver for the e field.
func (r *subscriptionResolver) E(ctx context.Context) (<-chan *bool, error) {
	panic(fmt.Errorf("not implemented: E - e"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
